server:
  tomcat:
    threads:
      max: 100
      min-spare: 20
  port: 8004
spring:
  application:
    name: batch
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  devtools:
    restart:
      #热部署生效
      enabled: true
      log-condition-evaluation-delta: false
      quiet-period: 400ms #触发重启之前没有任何类路径更改所需的安静时间量。
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://124.70.213.14:3306/vitadb_test?useSSL=false&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: vitadba
    password: vitadba@KLD2020
    hikari:
      #最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      # 测试连接
      connection-test-query: SELECT 1
  #      connection-init-sql: set collation_connection=utf8mb4_unicode_ci
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2500MB
  #redis config
  redis:
    host: 127.0.0.1
    port: 6389
    password: 123456

    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 5
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc

logging:
  level:
    com.admin: debug
    org.springframework.data.mongodb.core: DEBUG

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**Mapper.xml
  #枚举转换
  #typeEnumsPackage: com.knd.enums

  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.knd.batch.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ASSIGN_UUID
      #数据库大写下划线转换
      capital-mode: false
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false

#配置这句话,控制台输出sql语句
management:
  endpoints:
    web:
      exposure:
        include: '*'

swagger:
  title: batch
  description: 批处理
  service-url: http://127.0.0.1:8004  # /swagger-ui.html
  contact: sy
  version: 0.0.1-beta

eureka:
  instance:
    health-check-url: http://localhost:${server.port}/actuator/health
    status-page-url: http://localhost:${server.port}/actuator/info
    home-page-url: http://localhost:${server.port}
    metadata-map:
      cluster: ${spring.application.name}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


upload:
  imagesTypeList: png,jpg
  videoTypeList: mp4
  appTypeList: apk

OBS:
  # 可以不带协议、也可以带协议
  endPoint: obs.cn-east-3.myhuaweicloud.com
  ak: XXAQGOL8KYHZVJJJ6E92
  sk: SswmAFw71WhxAw0ASValmMRL7rE6ijRzBAd3g4v4
  imageFoldername: pro/image/
  videoFoldername: pro/video/
  appFoldername: pro/app/
  obsPrefix: pro/
  bucketname: knd-vita-test

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false


# 开启服务熔断 hystrix
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 20000 # feign 的超时设置
        readTimeout: 20000
qiniu:
  accessKey: dAeBe58B5WgO4K1zR6UNgnMD6mxlqLzRKx1X-OIy
  secretKey: eaO7d3NnPC7F1np07zlrW4sjXYOsZX6xquVaGiCP
  appId: fob0pqv07