server:
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 8096
    threads:
      max: 100
      min-spare: 20
  port: 8002
spring:
  application:
    name: front
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  devtools:
    restart:
      #热部署生效
      enabled: true
      log-condition-evaluation-delta: false
      quiet-period: 400ms #触发重启之前没有任何类路径更改所需的安静时间量。
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    #url: jdbc:mysql://124.70.213.14:3306/vitadb_dev?useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    #username: vitadb_dev
    #password: Vitadb-dev
    url: jdbc:mysql://124.70.213.14:3306/vitadb_new?useSSL=false&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: vitadba
    password: vitadba@KLD2020

    hikari:
      #最小空闲连接数量
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      # 测试连接
      connection-test-query: SELECT 1
  #      connection-init-sql: set collation_connection=utf8mb4_unicode_ci
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2500MB
  #redis config
  redis:
    ##    host: 172.168.1.184
    #    host: 172.0.0.1
    #    port: 6379
    ##    password: hxRedis@test
    #    password: 853396015
    #    //
    #    host: 172.168.1.184
    host: 127.0.0.1
    port: 6379
    #    password: hxRedis@test
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 5

logging:
  level:
    com.admin: debug
    org.springframework.data.mongodb.core: DEBUG

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**Mapper.xml
  #枚举转换
  #typeEnumsPackage: com.knd.enums

  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.knd.front.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #逻辑删除配置
      #      logic-delete-field: deleted
      #      logic-delete-value: 1
      #      logic-not-delete-value: 0
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ASSIGN_ID
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      #      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      capital-mode: false
    #自定义填充策略接口实现
    #meta-object-handler: com.finchley.cloud.xxx
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置这句话,控制台输出sql语句
management:
  endpoints:
    web:
      exposure:
        include: '*'

swagger:
  title: front
  description: 移动端
  service-url: http://127.0.0.1:8002  # /swagger-ui.html
  contact: sy
  version: 0.0.1-beta

eureka:
  instance:
    health-check-url: http://localhost:${server.port}/actuator/health
    status-page-url: http://localhost:${server.port}/actuator/info
    home-page-url: http://localhost:${server.port}
    metadata-map:
      cluster: ${spring.application.name}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


time: 5
appId: A1484E14E26B2289AC33214E5CF535BC
#msgSms:
#  url: https://rtcsms.cn-north-1.myhuaweicloud.com:10743/sms/batchSendSms/v1
#  appKey: g04sSaynLK15pGAt77v0lwvuGqxX
#  appSecret: Z4nP8fYAXcuVI0ibKHpBq1NrDVWE
#  sender: 8820080629059
#  resetTemplateId: f37ef17ea8964b60bdd3a871bb16c530
#  registerTemplateId: da87b115b1534b33a62e7dfbd5afa6d9

msgSms:
  url: https://rtcsms.cn-north-1.myhuaweicloud.com:10743/sms/batchSendSms/v1
  appKey: b9j2Z7hV3okMu6nTDvK3bMcSxSwE
  appSecret: 4YN3GW54LTZIKxm0d0WjWIOrADJz
  sender: 8820081034899
  resetTemplateId: 7fe9692020194591b05aa09cec8de0f8
  registerTemplateId: c1775094d42c4e359a9e583fe930368b
  receivingCodeTemplateId: 8f2f89c9959c46dab883f061ce603164
  loginCodeTemplateId: 779098dfd7f641e0a5a87d402ce1b0b2


upload:
  #  文件最大500M
  AttachFileMaxSize: 500
  #  视频只支持MP4
  imagesTypeList: png,jpg
  videoTypeList: mp4
  appTypeList: apk
  FileImagesPath: https://knd-vita-dev.obs.cn-east-3.myhuaweicloud.com/pro/image/
  FileVideoPath: https://knd-vita-dev.obs.cn-east-3.myhuaweicloud.com/pro/video/
  FileAppPath: https://knd-vita-dev.obs.cn-east-3.myhuaweicloud.com/pro/app/

OBS:
  # 可以不带协议、也可以带协议
  endPoint: obs.cn-east-3.myhuaweicloud.com
  ak: XXAQGOL8KYHZVJJJ6E92
  sk: SswmAFw71WhxAw0ASValmMRL7rE6ijRzBAd3g4v4
  imageFoldername: pro/image/
  videoFoldername: pro/video/
  appFoldername: pro/app/
  bucketname: knd-vita-dev

JPush:
  app_key: 7e13fdf7f0f5ffbe5ea8527d
  master_secret: b0173a5803ee1a031a965ad2

pay:
  order:
    timeOut: 30 #订单超时时间 单位(分钟)


hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false


# 开启服务熔断 hystrix
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 20000 # feign 的超时设置
        readTimeout: 20000
amap:
  web:
    key: 3aed1da3ce642a9f7523f8ca701d6023

qiniu:
  accessKey: dAeBe58B5WgO4K1zR6UNgnMD6mxlqLzRKx1X-OIy
  secretKey: eaO7d3NnPC7F1np07zlrW4sjXYOsZX6xquVaGiCP
  appId: fob0pqv07

deppon:
  customCode: 891728725
  sign: BPFU
  companyCode: EWBCZKNDZN
  appKey: b204929204257a3ec7e538aeb017edb0
  trajectoryUrl: http://dpsanbox.deppon.com/sandbox-web/standard-order/newTraceQuery.action
  queryOrderUrl: http://dpsanbox.deppon.com/sandbox-web/standard-order/queryOrder.action

ane:
  code: CSCODE
  secretKey: b5e05c75028ba56ab60bf5629862299a
  trajectoryUrl: http://122.144.220.210:20245/aneop/services/logisticsQuery/new/query

judge: true